# docker-compose.yml
services:
  # --- 1. NUESTRO CLÚSTER MONGODB  ---
  mongo1:
    image: mongo:latest
    container_name: mongo1
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster
    volumes:
      - mongo1-data:/data/db

  mongo2:
    image: mongo:latest
    container_name: mongo2
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27018:27017"
    networks:
      - mongo-cluster
    volumes:
      - mongo2-data:/data/db

  mongo3:
    image: mongo:latest
    container_name: mongo3
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27019:27017"
    networks:
      - mongo-cluster
    volumes:
      - mongo3-data:/data/db

  # --- 2. LA APLICACIÓN WEB (NUEVA) ---
  webapp:
    build: ./app
    # CORRECCIÓN: Desplegamos 3 réplicas para el balanceo
    deploy:
      replicas: 3
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongo-cluster

  # --- 3. EL BALANCEADOR DE CARGA  ---
  load-balancer:
    image: nginx:latest
    ports:
      - "80:80" # El balanceador escucha en el puerto 80 
    volumes:
      # Montamos nuestro archivo de config de Nginx
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - webapp
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data: